### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by jolas-rui** [da-anda/hass-io-addons#2]
I tried to install your addon on the latest HASSIO but it just got stuck on install and nothing more. I am a newbie on HASSIO but I have worked before with RPI and busware TPUART successfuly. Now I am trying to use an ABB interface that I usually use for working with ETS. 
Do you happen to know why the installation froze or where can I get some diagnostics to understand what is wrong?
Thanks in advance, mate.

**Comment by jolas-rui** [comment]
After trying a lot, I managed to get this to work with BUSWARE TPUART, that I happened to have on another device. I could not get the ABB USB connection to work...
Also, the Busware connection has proven not to be 100% reliable as, after rebooting, sometimes the gateway is not accessible on Hassio.
Good luck!

**Comment by maressl** [comment]
Im getting error in Home Assistant: 
ERROR (SyncWorker_2) [hassio.docker.addon] Can't build ecaeb50e/armhf-addon-knxd:0.2.12: The command '/bin/sh -c set -xe     && apk update     && apk add --no-cache

So i cant install it on version 0.82.1 and also not on 0.83 beta

Any ideas?

**Comment by maressl** [comment]
I tried to install manually and i see error:  

llserial.cpp: In member function 'virtual void LLserial::start()':
llserial.cpp:138:33: error: too few arguments to function 'void restore_low_latency(int, low_latency_save*, bool)'

usb.cpp:49:5: warning: 'void libusb_set_debug(libusb_context*, int)' is deprecated: Use libusb_set_option instead [-Wdeprecated-declarations]

if this helps.

**Comment by da-anda** [comment]
sorry guys for not responding. I had misconfigured my github settings and didn't get any notifications what so ever from this repository.

Regarding compile/runtime errors - those might have been temporary issues of knxd. When compiling the container it always fetches the most recent stable version of knxd and not just a specific version.

As for USB vs TPUART. Since I couldn't test real USB KNX interfaces I just assumed they might also work. I just merged a PR that should hopefully fix it - so if you still would like to try a commercial USB interface, try version 0.3.2
