### ISSUE TITLE
knxd quits with permission issues after 0.4.6 upgrade 

### ISSUE THREAD

**Issue by kabukimandelux** [da-anda/hass-io-addons#32]
Since upgrading to 0.4.6, knxd quits with the following: 

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/2-init-config
/package/admin/s6-overlay-3.1.2.1/etc/s6-rc/scripts/cont-init: line 14: /etc/cont-init.d/2-init-config: Permission denied
cont-init: info: /etc/cont-init.d/2-init-config exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Trying to downgrade to 0.4.5 did not solve the issue.
I use a busware usb tpuart.

**Comment by da-anda** [comment]
thanks for reporting. I noticed this issue with 0.4.5 and the bump of the Alpine base image to 3.16, which is the reason I reverted the base-image bump in 0.4.6 again. So 0.4.6 should work just fine.
My guess is that your HA installation might have still picked up the 0.4.5 image when it tried to install 0.4.6. I haven't found out yet how I could bind a specific image version to a specific release, but HA doesn't seem to care if the image on the server actually differs from the currently installed image. The second there is a change of the version number in the manifest, HA will download whatever image is present on the server, even if it's not yet the new image because it is still being compiled by the github workflow.
Deployment is as follows:
- I commit a change, like the version bump of knxd to github
- github workflow workers kick in and start to compile the new add-on images
- in the meantime, HA notices already the new version number on github and shows that an update is available
- if you now hit install, HA thinks it will install the new version, even though the github worker hasn't compiled the add-on image yet

Please try to uninstall the add-on and install it again. Hopefully the supervisor will pick up the new add-on image then.

**Comment by da-anda** [comment]
shit, I now see the same issue on 0.4.6. No idea why since nothing in this regard changed. I'll investigate. Sorry for the bug

**Comment by da-anda** [comment]
so I compiled it locally directly on my PI and it's running fine

**Comment by kabukimandelux** [comment]
No prob, downgraded to 0.4.4. All fine again. Thanks for all the work!

**Comment by da-anda** [comment]
startup issues should finally be resolved in 0.4.7 now. Sorry for the inconvenience with the broken update.

**Comment by kabukimandelux** [comment]
Issue resolved for me, thanks for the update
